### ISSUE TITLE
Unify Ordinarium

### ISSUE THREAD

**Issue by FAJ-Munich** [FAJ-Munich/divinum-officium#16]
1. Similar to Completorium (provided by @mbab commit 0c42509d0b9496e1c30fda6d5b0dc555cc87d075 ) unify the Ordinarium files for all the Hours and versions
2. Provide extra rubrical instructions for Incipit et Pater noster etc.

**Comment by FAJ-Munich** [comment]
Dear @mbab
I've learned from some of your comments that you are already working on this enhancement and I have fiddled around with some of the 2nd improvement to the Ordo I have in mind on my branches. Before I interfere unnecessarily with your developments could you indicate how far you are in this task? 

PS:  Since I don't know how to send you an email via github and I didn't want this to draw everybody's attention, I've tried to set up a Project and Issues within my fork. Hope this message reaches you. Looking forward to collaborate on this and especially the Monastic offices 1617 / 1930 if you are interested.

**Comment by mbab** [comment]
> Dear @mbab I've learned from some of your comments that you are already working on this enhancement and I have fiddled around with some of the 2nd improvement to the Ordo I have in mind on my branches. Before I interfere unnecessarily with your developments could you indicate how far you are in this task?

I have this in plan only (even from few years).

>
> PS: Since I don't know how to send you an email via github and I didn't want this to draw everybody's attention, I've tried to set up a Project and Issues within my fork. Hope this message reaches you. Looking forward to collaborate on this and especially the Monastic offices 1617 / 1930 if you are interested.

I'm willing to communicate by email, You can find my address using `git log -1 eb7fd16`

**Comment by FAJ-Munich** [comment]
With 3343e99ff7c769069dd7042aa285338b737cd105 being merged, Matins and Prime remain to be done.

**Comment by mbab** [comment]
@FAJ-Munich Please be aware my [proposition](https://github.com/DivinumOfficium/divinum-officium/discussions/3800)

> I'm willing to communicate by email, You can find my address using `git log -1 eb7fd16`

Do You find address?
